services:
  node-dev-env:
    build: .
    command: npm run dev
    ports: 
      - 5173:5173
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    container_name: node-dev-env

volumes:
  node_modules: