GET http://localhost:3001/api/clients/

###
POST http://localhost:3001/api/clients/ 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlYW4iLCJpZCI6IjY4MTY4ZDlkMTMwZTBlMWMwNzllNjg4YiIsImlhdCI6MTc0NjM2NzczMywiZXhwIjoxNzQ2MzcxMzMzfQ.XMAdUij-dNKw9F4L3nLgNCytnh0ehjojGBK5-9njJ9g


{
    "name": "BELLMOR",
    "subscriber": true
}

###
DELETE http://localhost:3001/api/clients/2 HTTP/1.1
#content-type: application/json